### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by twaltersr** [efpe/amazon-alexa-lg-tv#12]
C:\Users\Yoga\Desktop\TB>c:\Python27\python.exe alexa-tv.py
Traceback (most recent call last):
  File "alexa-tv.py", line 13, in <module>
    import fauxmo
  File "C:\Users\Yoga\Desktop\TB\fauxmo.py", line 31, in <module>
    import requests
ImportError: No module named requests

**Comment by twaltersr** [comment]
i was able to run py -m pip install requests and get past the error No module named requests.

Now getting this

C:\Users\Yoga\Desktop\TB>c:\Python27\python.exe alexa-tv.py
Traceback (most recent call last):
  File "alexa-tv.py", line 47, in <module>
    p = fauxmo.poller()
  File "C:\Users\Yoga\Desktop\TB\fauxmo.py", line 67, in __init__
    self.poller = select.poll()
AttributeError: 'module' object has no attribute 'poll'

**Comment by henrik** [comment]
Thank you. I got the same errors on my Mac.

First I installed "requests" much like you said: `sudo pip install requests`

Then to fix the poll error, I had to reinstall a Python with (apparently a bit broken on macOS) polling enabled [based on this](https://github.com/google/pyringe/issues/14#issuecomment-57856541):

```
brew install python --with-poll  # Install Python using Homebrew.
hash -r python  # To fix Python after reinstalling
```

Now I instead get this error, though: https://github.com/efpe/amazon-alexa-lg-tv/issues/2
