### ISSUE TITLE
cannot find module lgtv

### ISSUE THREAD

**Issue by jfarcher** [efpe/amazon-alexa-lg-tv#5]
on running tv off i'm getting the following error:

 module.js:471
    throw err;
    ^

Error: Cannot find module 'lgtv'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/amazon-alexa-lg-tv/tv_shutdown.js:1:70)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
TV turned off!

**Comment by jfarcher** [comment]
did an npm install lgtv without the -g and it seems to work, although the off feature is hit and miss. Random IP addresses showing up in the logs which aren't the TV.
Going to debug a little to see if i can get to the bottom of it.

**Comment by khiles** [comment]
Mine same it seems to find any device on network but not my lg tv its on 192.168.1.127 but it keeps going to 192.168.1.115 which is my chromcast

**Comment by akhan23wgu** [comment]
I had the same issue. Installed Nodejs 4 and it worked.

**Comment by paulojhsousa** [comment]
Same issue here. It continues to listen to a wrong IP addr. Did you guys manage to find a workaround?
