### ISSUE TITLE
Missing requirement in README, later error in fauxmo line 67

### ISSUE THREAD

**Issue by protogilly** [efpe/amazon-alexa-lg-tv#7]
Platform: Windows 10
Python version 2.7.13

It should be noted in the readme that you should pip install requests as a requirement.

Also, when running in windows, I get the following error when trying to run the script:

Traceback (most recent call last):
  File "alexa-tv.py", line 47, in <module>
    p = fauxmo.poller()
  File "C:\Scripts\amazon-alexa-lg-tv-master\fauxmo.py", line 67, in __init__
    self.poller = select.poll()
AttributeError: 'module' object has no attribute 'poll'

This is caused because poll is not properly implemented in the Windows or MacOS versions of python. The newest version of fauxmo fixes this problem.

**Comment by efpe** [comment]
Poll is not available on Windows. You need either Linux or OS X to use this right now. I don't know about newer version, will try to take a look. 

Maybe we can use the pypi package: https://pypi.python.org/pypi/fauxmo

**Comment by akhan23wgu** [comment]
@efpe have you tried looking into the pypi package? If not, I might get a chance later next week to try it out.

**Comment by efpe** [comment]
hi, sorry not yet. I'm behind with everything but will try to catch up soon. sorry guys
